gText_Olive_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "How are things back home on ILLOS?\p"
	.string "My name is OLIVE.\p"
	.string "$"

gText_Olive_Pokemon::
	.string "This is what we call a POKéMON.\p"
	.string "\n"
	.string "$"

gText_Olive_MainSpeech::
	.string "Back on our island, you're used to\n"
	.string "seeing these creatures in the fields,\l"
	.string "pulling plows and carrying cargo.\p"
	.string "To most ILLIANS, they're just tools.\n"
	.string "Machines made of muscle.\p"
	.string "But out here, away from home...\n"
	.string "I've discovered something wonderful.\p"
	.string "They feel joy. They feel sorrow.\n"
	.string "They are capable of incredible bonds.\p"
	.string "I know it sounds strange to someone\n"
	.string "who grew up in PRASINIA, but...\l"
	.string "they are so much more than livestock.\p"
	.string "I've dedicated my life to proving that.\p"
	.string "$"

gText_Olive_AndYouAre::
	.string "Ah, but listen to me ramble.\p"
	.string "I'm sorry, my mind wanders these days.\p"
	.string "It's been so many years since I left.\n"
	.string "Let me take a look at you...\p"
  .string "$"

gText_Olive_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Olive_WhatsYourName::
	.string "All right.\n"
	.string "What's your name again?$"

gText_Olive_SoItsPlayer::
	.string "So you're {PLAYER}{KUN}?$"

gText_Olive_YourePlayer::
	.string "Ah, of course!\p"
	.string "You're the kid from next door!\n"
	.string "You've grown so much.\p"
	.string "I remember now!\p"
	.string "$"

gText_Olive_AreYouReady::
	.string "All right. Are you ready?\p"
	.string "You've never left your hometown, but\n"
	.string "a whole world is waiting for you.\p"
	.string "Keep an open mind, and see this\n"
	.string "world with fresh eyes.\p"
	.string "I'm returning to ILLOS today.\n"
	.string "Come visit my lab when you're ready.\p"
	.string "$"
